### ISSUE TITLE
Feature request: ability to translate strings in the Vacuum state

### ISSUE THREAD

**Issue by tigers75** [sh00t2kill/dolphin-robot#112]
Hi, I made a PR with the italian translation, I'd like to translate also the strings for the state and mode inside of the vacuum object (that's "floor only", "water line", etc).
Is this possible?

**Comment by elad-bar** [comment]
please check  the new release [v0.4.0](https://github.com/sh00t2kill/dolphin-robot/releases/tag/v0.4.0),
please let me know if it works for you

thanks

**Comment by elad-bar** [comment]
@tigers75 can you please update update the translation following the changes I introduced lately?

thanks

**Comment by tigers75** [comment]
Will do for sure. I'm having trouble on finding the files (maybe because the repository changed its location? I saw them the other day but now if if go to the repository form inside HACS I can't find them .
I'll look into it in this weekend

**Comment by elad-bar** [comment]
it was consolidated into single translation file, component/translations.json and translations/{lang}.json

**Comment by elad-bar** [comment]
add ability to translate also component's names, if you would like to add it

**Comment by elad-bar** [comment]
can we close that issue?

thanks

**Comment by tigers75** [comment]
I still see the cleaning mode in English in the vacuum card (but they're translated if I open it). Is something that can be translated? 
Also sorry but I don't know what to add to translate "components".

![Screenshot_20230711_080059_Home Assistant](https://github.com/sh00t2kill/dolphin-robot/assets/37505492/5f160edc-5c18-43df-9577-bc84a687969f)

**Comment by tigers75** [comment]
Yes, they're translated correctly, except for the name of the entities but that's correct I think. 
![Screenshot_20230711_170304_Home Assistant](https://github.com/sh00t2kill/dolphin-robot/assets/37505492/0df32394-dcd3-44a3-8684-e444aadadcfc)

I'll close the issue.

**Comment by elad-bar** [comment]
I will investigate it, thanks
