### ISSUE TITLE
Feature: Constant home 

### ISSUE THREAD

**Issue by ofirda** [sh00t2kill/dolphin-robot#129]
I have a m600 on a pool with boundaries that are unreachable, can I specify a constant locaiton (near my stairs) to set as "home"?

**Comment by sh00t2kill** [comment]
There is no way to actually determine where in the pool the robot is. 

It's different to a vacuum in that manner. The home functionality is actually pick up mode.

**Comment by elad-bar** [comment]
as mentioned by @sh00t2kill, no option to know where the robot is, therefore, we cannot even try to drive it (manually) to the same location,
I think that given the variables available in each cycle (robot slipped, hit an obstacle) Mytronics cannot calculate the path back, it would be much easier to tell you "just poll the cable and the robot will get to you" rather adding more sensors to fix it.

although it should be nice adjustment, I will close that issue, sorry,
if things will change in the future from Mytronics, pls reopen that issue.
