### ISSUE TITLE
Feature Req: Halt robot cleaning attempt when out of pool

### ISSUE THREAD

**Issue by ofirda** [sh00t2kill/dolphin-robot#130]
My m600 starts cleanng and moves a bit when on a weekly program OUTSIDE of the pool water, making it hard for me to leave it in stand without turning off the weekly progrmaing, which then requires me to turn back on when in water
How can we refrain the robot to not attempt to clean when outside of pool without disabling weekly program

**Comment by sh00t2kill** [comment]
I have raised this as an issue with maytronics. 

Their suggestion to me was to turn it off. Not overly helpful but the short answer to your question is not possible without disabling the schedule.

**Comment by elad-bar** [comment]
as mentioned by @sh00t2kill, no option to know where the robot is, therefore, we cannot even try to drive it (manually) to the same location,
I think that given the variables available in each cycle (robot slipped, hit an obstacle) Mytronics cannot calculate the path back, it would be much easier to tell you "just poll the cable and the robot will get to you" rather adding more sensors to fix it.

although it should be nice adjustment, I will close that issue, sorry,
if things will change in the future from Mytronics, pls reopen that issue.

**Comment by ofirda** [comment]
Thanks @elad-bar 
It makes no sense that there is no "water sensor" before activating the device
it moves in its own stand, rips the rubber and the stand
We have to find a solution for this ASAP

**Comment by sh00t2kill** [comment]
@ofirda contact maytronics. This is an issue with their platform, not the HA component.

**Comment by elad-bar** [comment]
Will have better answer by end of the day, but most likely they will tell you, for that you need m700,
An alternative solution is to attach to it wireless water leak sensor

**Comment by ofirda** [comment]
complicated- you will need one that is connected to it and reports over WIFI that is "in water" to block cleaning - you will have to program that via HA and not via the app, probably easier to disable cleaning

**Comment by sh00t2kill** [comment]
@ofirda we have made a decision to remove all the scheduling control from HA, as using an automation or a node red flow gives far more granular control.

To this end there are 2 options.
1) Use the mobile app for scheduling, but turn the robot off when its not in the water -- ie remove power. This is how I have started operating as my M600 does the same thing when sitting on a trolley.
2) Use the scheduling component with an input_boolean toggle condition to override them -- and toggle this when the robot is out of the water manually.

Neither are the ideal situation, but unfortunately it seems that models prior to the M700 do not provide this information.


Its worth adding that this happened with my M600 will before we started working on this component -- its not really a HA integration problem so much as a design fault with the platform.

**Comment by ofirda** [comment]
Understood
What / where is the input boolean scheduling switch? Perhaps I can automate
it somehow

**Comment by sh00t2kill** [comment]
> 

there isnt one, you would need to create it in HA.

**Comment by elad-bar** [comment]
Maybe we can move that discussion to discord, I actually have an out of the box solution for you, instead of know when the robot is in the water, maybe you should know when the tobot is out of the water,
Are you locating your robot in specific place?
In case you do, think about something that will work for you and will make HA to know the robot is there - NFC, Magnetic sensor, weight sensor, laser beam, camera that will scan QR code or trained to identify the robot...

**Comment by ofirda** [comment]
I will just make a physical switch on trolly to disconnect power once there
My question though remains where is that boolean parameter you mentioned?
Easier to press that rather then clicking and disabling each day

**Comment by sh00t2kill** [comment]
@ofirda I was referring to this: https://www.home-assistant.io/integrations/input_boolean/

ie set it up manually, and use it in your integrations/scheduler component, and delete the schedule from the MyDolphin Plus app.

I am closing this issue, please join us on Discord and we can chat about other potential options for you.

https://discord.com/invite/sS4gDj2QWP
