### ISSUE TITLE
Nothing works except for the start command

### ISSUE THREAD

**Issue by l2jalbe** [sh00t2kill/dolphin-robot#131]
"Hi, I have a problem with the robot (E40i, myDolphin+ always connected). From HA, I can read all the data, but I can only send the start command. I can't give it any other commands. I try to change its settings through the 'vacuum' service, but it doesn't respond to anything. I can't even stop it. For example, with this automation, it starts but doesn't change the fan speed."

alias: Robot Piscina (Seconda pulizia)
description: >-
  Avvia il robottino alle ore 15 in modalità solo fondale tutti i giorni (durata
  1 ora)
trigger:
  - platform: time
    at: "15:00:00"
condition: []
action:
  - service: vacuum.set_fan_speed
    data:
      fan_speed: short
    target:
      entity_id:
        - vacuum.pola_pesciolino
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: vacuum.start
    data: {}
    target:
      entity_id:
        - vacuum.pola_pesciolino
mode: single

**Comment by sh00t2kill** [comment]
I'll have to check to be 100% sure but I don't believe fan speed is implemented as it doesn't actually do anything.. the pool robot doesn't have a fan or an adjustable level of cleaning.


Re stop; can you stop it from within the mydolphin app once a job is started? Allegedly, not all robots support this.

**Comment by gkyprios** [comment]
I have the same issue with my M600. The app works fine for starting, stopping and changing Cleaning Mode. But I can only start the robot through HA.

**Comment by sh00t2kill** [comment]
Confirmed with mine too. Recently introduced bug.

@elad-bar

**Comment by elad-bar** [comment]
We can keep this issue opened, it's still an item mentioned in the status scope, need to test action as the integration is WIP

**Comment by elad-bar** [comment]
removing the regression tag as it didn't work before

**Comment by elad-bar** [comment]
pls check v1.0.0 and report whether it's working for you

thanks

**Comment by gkyprios** [comment]
I can confirm that everything working for me now. Never better!

**Comment by l2jalbe** [comment]
I confirm too that everything works with my E40i.
I ve noticed that when I change the "fan speed" the robot start immediately the cleaning and do the program related to the "fan speed" mode selected.
In case of automation we can simply send a vacuum comand to set the fan speed and the robot will change and start
