### ISSUE TITLE
Need help with tralnslation

### ISSUE THREAD

**Issue by tigers75** [sh00t2kill/dolphin-robot#147]
My Dolphin model doesn't have all the features, so I have some doubt on how to translate some of the strings:

- "cycle_time_pickup": what's the meaning of pickup here? Is it "picking the robot out of the water" for maintenance, cleaning, etc.? Or is it more like "picking debris from the pool"?
- *Impeller 1 under load*: here what does it mean by "under load"? Is it "it's working under the required speed" in opposition to the previous string "Impeller overload"? Or does it mean "it's under load, but that's what it should do, and it's fine"?

At the moment I made a literal translation, but it's a bit ambiguous and I think I could improve it.

**Comment by elad-bar** [comment]
"picking the robot out of the water" is more accurate,
"under load" - robot cannot drive as surface is too slippery

**Comment by elad-bar** [comment]
Is it still relevant or can we close the issue?

Thanks
