### ISSUE TITLE
Login to account without a password

### ISSUE THREAD

**Issue by pbouwen3** [sh00t2kill/dolphin-robot#155]
My Dolphin Plus account has no password, I can only login by receiving a security code on my email address.
Also, there's no option to configure a password.

Do you think this could be supported?

**Comment by sh00t2kill** [comment]
Are you sure there's no way to set a password?

That would require you re-entering the code every now and then which would be ... annoying

**Comment by elad-bar** [comment]
Are you using google account (social login)?

**Comment by pbouwen3** [comment]
Via the web there is indeed no option to set it anywhere. (https://www.maytronics.com/en-us/login/)
Social login is not used.

BUT upon logging out of the app, from there I can see there's a link where I can create a password for my account.
So that should work and this issue can be closed.
