### ISSUE TITLE
Home assistant not correctly displays translated states

### ISSUE THREAD

**Issue by tigers75** [sh00t2kill/dolphin-robot#159]
The new version with full translation is out and I'm scratching my head: as I see the sensor names are fully translated now, and that's the only way to refer to the sensor.
This is maybe good but this means that if I improve or modify the translation the sensor will change name too.
I don't know if this is the expected behavior.

Also there's still some problem with displaying translated status:
This is what I see when using a template to extract the value:
![image](https://github.com/sh00t2kill/dolphin-robot/assets/37505492/b00b4f1c-755b-4db8-8d68-adc0583169d1)
It says "floor" in original language, it should be "pavimento"

I believe this is a problem with HA since I see this while templating:
![image](https://github.com/sh00t2kill/dolphin-robot/assets/37505492/57ee9fdf-a09d-4663-8a71-f13427977e01)
BUT the entity card of the same sensor shows it correctly translated:
![image](https://github.com/sh00t2kill/dolphin-robot/assets/37505492/163c43a4-1d66-4ce8-bcb9-cb7d4c5bfef6)

**Comment by elad-bar** [comment]
It sound like a general issue of that process in HA, not sure it will change after it was created as it has unique id that is not dependent on translated name, 
If it happens I suggest to post a bug in HA repo

**Comment by tigers75** [comment]
It did change name when I upgraded to the new version that includes the italian translation. It was named with *original_language_name* as in the translation file before I upgraded.

**Comment by elad-bar** [comment]
Sounds correct behavior, it doesn't intrdouce breaking changes

**Comment by tigers75** [comment]
> It sound like a general issue of that process in HA, not sure it will change after it was created as it has unique id that is not dependent on translated name, If it happens I suggest to post a bug in HA repo

There's one already with a long list of similar issues starting from 2023.4 version, still not fixed as I can see.

**Comment by tigers75** [comment]
> Sounds correct behavior, it doesn't intrdouce breaking changes

Makes sense, in fact I never experienced add-ins that were not translated form the start. Still it's annoying because it forces to modify all the dashboards and automations that use the entities that changed name.

**Comment by elad-bar** [comment]
nothing to do, correct behaviour
