### ISSUE TITLE
Where can I find me Dolphin Plus account password?

### ISSUE THREAD

**Issue by guyliorha** [sh00t2kill/dolphin-robot#166]
Where can I find me Dolphin Plus account password?

**Comment by sh00t2kill** [comment]
Im not sure exactly what you are asling gor.

If you have forgotten your password but HA is still working, credentials are stored in hidden files in the .storage directory

**Comment by elad-bar** [comment]
If you forgot password, you can restore it through the mobile app, don't forget to update the integration afterwards.

If you would like to use the integration for the first time and logged in with social login, it is not supported, you will need to create an account with email and password, then use it

Does it address your need?
If not, pls provide more details

**Comment by guyliorha** [comment]
> If you forgot password, you can restore it through the mobile app, don't forget to update the integration afterwards.
> 
> If you would like to use the integration for the first time and logged in with social login, it is not supported, you will need to create an account with email and password, then use it
> 
> Does it address your need? If not, pls provide more details

That was the issue, thanks!
