### ISSUE TITLE
Errors being logged after upgrading to latest release as per Jan 6th

### ISSUE THREAD

**Issue by MaxVonEvil** [sh00t2kill/dolphin-robot#167]
Seems to be working, yet getting 1700+ of these errors in the system log since upgrade

Logger: custom_components.mydolphin_plus.managers.coordinator
Source: custom_components/mydolphin_plus/managers/coordinator.py:413
Integration: MyDolphin Plus
First occurred: January 6, 2024 at 08:17:06 (1718 occurrences)
Last logged: 20:20:29

Failed to extract data for MyDolphinPlusSensorEntityDescription(key='temperature', device_class=<SensorDeviceClass.TEMPERATURE: 'temperature'>, entity_category=None, entity_registry_enabled_default=True, entity_registry_visible_default=True, force_update=False, icon=None, has_entity_name=False, name='Temperature', translation_key='temperature', unit_of_measurement=None, platform=<Platform.SENSOR: 'sensor'>, last_reset=None, native_unit_of_measurement=<UnitOfTemperature.CELSIUS: '°C'>, options=None, state_class=<SensorStateClass.MEASUREMENT: 'measurement'>, suggested_display_precision=None, suggested_unit_of_measurement=None), Error: 'str' object has no attribute 'get', Line: 407

**Comment by elad-bar** [comment]
Please provide diagnostic file and logs with debug log level, need to understand what is the data that causes it

**Comment by sh00t2kill** [comment]
@elad-bar looks like we need to check if the temperature data is in the payload. Must not be there in every case.

**Comment by elad-bar** [comment]
It is available for M700 only, it is not empty according to the error but it is string, so that is why i need the information yo understand why it is different than what we knew before

**Comment by elad-bar** [comment]
checked the code again, sensor should be available for M700 only with that information, if it throws an expection it is because of something unhandled, for that i will need the logs (in debug level) and diagnostic file

thanks

**Comment by sh00t2kill** [comment]
@MaxVonEvil following up on this one -- are you able to please provide debug logs and diagnostics file?

**Comment by MaxVonEvil** [comment]
Sorry, been away for a while - let me check this weekend if I still get these.

**Comment by elad-bar** [comment]
@MaxVonEvil any updates?

thanks

**Comment by MaxVonEvil** [comment]
Yeah, could you let me know where to get the debug log?

**Comment by elad-bar** [comment]
Are you on the latest version of HA and integration?

**Comment by MaxVonEvil** [comment]
Almost, I'm on HA: 2024.1.6, Dolphin integration: 1.0.8
I usually stagger updates of platform and integrations 30 days to catch as many bugfixes as posible

**Comment by elad-bar** [comment]
Integration is on version behind as well as HA, pls report soon with latest or we will need to close bug as no additional ppl reported it

Thanks

**Comment by MaxVonEvil** [comment]
Okay, so this might be a stupid question repeated - how and where do I get the debug log? I know to enable debugging on the integration, but where's the debug log located?

**Comment by elad-bar** [comment]
if someone is asking same question, it's not stupid - probably something make that person ask again, just need to understand the why :).

in the root directory of the HA config, if you set it to /config, it will be there named homeassistant.log,
another option - if you enable debug logs from the integration, once you will disable the debug log, it will download the logs as well from the browser.

this is the out-of-the-box logging solution of HA, relevant to all integrations.

in different integrations i have mentioned the above in the troubleshoot section of readme, look like it should be added here as well.

**Comment by sh00t2kill** [comment]
Im still a bit old fashioned and wed to doing stuff via CLI, i blame my linux brain.

Add this to config:
```
logger:
  default: warning
  logs:
    custom_components.mydolphin_plus: debug
```    

Restart HA

then via the ssh addon;
`cat /config/homeassistant.log | grep DEBUG`

**Comment by elad-bar** [comment]
'grep debug' will bring only line with that term, but when debug log is being requested it is also about all the other messages logs, as opposed to defualt which is warning and above

**Comment by sh00t2kill** [comment]
true, it should probably be grep mydolphin_plus

**Comment by MaxVonEvil** [comment]
Got it, thought there was a separate debug logfile, but okay, grepping it out of the main log is fine. Currently updating to latest HA and Mydolphin integration.

**Comment by MaxVonEvil** [comment]
So, after carefully monitoring this issue in the debug log files for the last few days, it seems this issue with the temperature reading, is no longer appearing. 

Tried several things like pulling the robot out mid job or disconnecting it from WiFi, however to no avail. 

Suppose.we can close this ticket. I will let you know if it reappears

**Comment by elad-bar** [comment]
Thanks for the update
