### ISSUE TITLE
Stop logging API credentials into log file by default

### ISSUE THREAD

**Issue by grillp** [sh00t2kill/dolphin-robot#168]
I see that whenever the API is called to update the cloud data, I see all my credentials dumped into the log file by default.

```2024-02-07 15:42:27.416 INFO (MainThread) [custom_components.mydolphin_plus.managers.rest_api] API Data updated: {'aws-token-encrypted-key': '<token>', 'serial_number': 'C6594RQM6L', 'login_token': '<real-token>', 'motor_unit_serial': 'Cxxxxxxxx', 'Token': '<real-toke>', 'SecretAccessKey': '<real access key>', 'Motor Unit Serial': 'Cxxx, 'Product Name': '99996710-AU', 'Product Description': 'DOLPHIN M700 AU', 'Application Name': 'myDolphin Plus', 'Registration Date': '20xx-xx-xxT07:10:00', 'Robot Name': 'Cleany', 'Is Registered': 'Y', 'Robot Family': 'M700'}```

I would only like to see that in my log files when I expressly set Log Level to DEBUG.

**Comment by sh00t2kill** [comment]
@grillp your change was merged as part of v1.0.9. Apologies i forgot to add it to the release notes.
