### ISSUE TITLE
Integration failed since 2024.2.X

### ISSUE THREAD

**Issue by jflefebvre06** [sh00t2kill/dolphin-robot#170]
Hello,

Since 2024.2.X integration failed on strartup

```
Logger: custom_components.mydolphin_plus.managers.aws_client
Source: custom_components/mydolphin_plus/managers/aws_client.py:501
Integration: MyDolphin Plus (documentation, issues)
First occurred: 08:39:53 (43 occurrences)
Last logged: 09:23:18

Status changed from 'Establishing connection to API' to 'Failed to access API'
```

```
Logger: custom_components.mydolphin_plus.managers.aws_client
Source: custom_components/mydolphin_plus/managers/aws_client.py:207
Integration: MyDolphin Plus (documentation, issues)
First occurred: 08:39:53 (43 occurrences)
Last logged: 09:23:18

Failed to initialize MyDolphin Plus WS, error: module 'ssl' has no attribute 'wrap_socket', line: 193
```

**Comment by tkroukamp** [comment]
I'm having the same problem.

**Comment by elad-bar** [comment]
Me too... will try to find out what causes it and fix it

**Comment by gdgib** [comment]
Same.  The error smells like an upgrade to an underlying library broke something that needs a minor fix.  Sadly not a high priority or I'd offer to fix it, too.

**Comment by sh00t2kill** [comment]
2024.2.x upgraded to python3.12 from 3.11. Thats the most likely culprit.

**Comment by gdgib** [comment]
A quick lookthrough, and it superficially looks like https://github.com/aws/aws-iot-device-sdk-python depends on paho, which appears to need an update.

**Comment by sh00t2kill** [comment]
yeah - looks like the aws iot sdk itself needs a change applied to it.

**Comment by elad-bar** [comment]
this version is no longer being maintained, need to switch to v2, good luck to us :)

**Comment by elad-bar** [comment]
I didn't find any document for that, and it works, just running few more tests and hope to release it by the end of the day

**Comment by elad-bar** [comment]
@sh00t2kill pls review PR

thanks

**Comment by sh00t2kill** [comment]
Reviewed, Merged, Released :D

**Comment by sh00t2kill** [comment]
Thanks for your assistance on this one @gdgib

**Comment by gdgib** [comment]
Any time.  My thanks to @elad-bar.  Well done!

**Comment by gdgib** [comment]
Well and you @sh00t2kill for the integration.  Not a small one, either.

**Comment by sh00t2kill** [comment]
It might have my name on it, but the majority of the credit goes to @elad-bar

**Comment by jflefebvre06** [comment]
Thanks for the fix, works fine

**Comment by tigers75** [comment]
I forced a manual update even if I already had 1.0.9 but I'm still getting an error and the addon is not loaded. Am I missing something?

**Comment by sh00t2kill** [comment]
> I forced a manual update even if I already had 1.0.9 but I'm still getting an error and the addon is not loaded. Am I missing something?

Just to rule out the obvious, have you restarted HA?

**Comment by tigers75** [comment]
Of course, multiple times. At restart I get this error:

`Logger: homeassistant.setup
Source: setup.py:221
First occurred: 09:00:23 (1 occurrences)
Last logged: 09:00:23

Setup failed for custom integration 'mydolphin_plus': Requirements for mydolphin_plus not found: ['awsiotsdk~=1.21.0', 'awscrt~=0.20.2'].`

**Comment by sh00t2kill** [comment]
Do you have any other custom components installed with those requirements?

Version mismatches with custom components can cause issues like this

**Comment by tigers75** [comment]
How do I know?

**Comment by elad-bar** [comment]
Can you pls edit the manifest.json installed in your HA of the custom component from:
['awsiotsdk~=1.21.0', 'awscrt~=0.20.2']
To:
['awsiotsdk', 'awscrt']

If it worked it means that there is conflict and it should get fixed once we will identify the conflict

**Comment by tigers75** [comment]
Now I get this error:
`Logger: homeassistant.setup
Source: setup.py:221
First occurred: 09:59:12 (1 occurrences)
Last logged: 09:59:12

Setup failed for custom integration 'mydolphin_plus': Requirements for mydolphin_plus not found: ['awscrt', 'awsiotsdk'].`

I noticed in my manifest the order was opposite to yours, I just deleted the version numbers and kept the order I had, I assume it should not matter. Should I try and invert them?

**Comment by tigers75** [comment]
Not sure what you mean: I'm running HA core in a docker container with the official HA release image, never had similar issues so far.

**Comment by sh00t2kill** [comment]
Can you try executing this command from inside the core container?

python -m pip show awsiotsdk

**Comment by tigers75** [comment]
I get this (this is WITH the modification to manifest.json as per previous message):

```
pi@raspberrypi:~ $ docker exec home-assistant python -m pip show awsiotsdk
WARNING: Package(s) not found: awsiotsdk
```

**Comment by sh00t2kill** [comment]
Can you manually install it via pip? Maybe there's some other strange conflict.

**Comment by tigers75** [comment]
I can try, but won't it get cancelled at the next update of the docker image?

**Comment by sh00t2kill** [comment]
Yeah but if it fails it will tell us why.

If it works, well I got nothing :)

**Comment by tigers75** [comment]
Can you give me some more detail on how to install?

**Comment by sh00t2kill** [comment]
python -m pip install awsiotsdk

**Comment by tigers75** [comment]
This is what I get:
`pi@raspberrypi:~ $ docker exec home-assistant python -m pip install awsiotsdk
Looking in indexes: https://pypi.org/simple, https://wheels.home-assistant.io/musllinux-index/
Collecting awsiotsdk
  Downloading awsiotsdk-1.21.0-py3-none-any.whl.metadata (4.2 kB)
Collecting awscrt==0.20.2 (from awsiotsdk)
  Downloading awscrt-0.20.2.tar.gz (32.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 32.1/32.1 MB 5.3 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Downloading awsiotsdk-1.21.0-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.5/73.5 kB 6.8 MB/s eta 0:00:00
Building wheels for collected packages: awscrt
  Building wheel for awscrt (setup.py): started
  Building wheel for awscrt (setup.py): finished with status 'error'
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [68 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-armv7l-cpython-312
      creating build/lib.linux-armv7l-cpython-312/awscrt
      copying awscrt/websocket.py -> build/lib.linux-armv7l-cpython-312/awscrt
      copying awscrt/s3.py -> build/lib.linux-armv7l-cpython-312/awscrt
      copying awscrt/http.py -> build/lib.linux-armv7l-cpython-312/awscrt
      copying awscrt/mqtt5.py -> build/lib.linux-armv7l-cpython-312/awscrt
      copying awscrt/exceptions.py -> build/lib.linux-armv7l-cpython-312/awscrt
      copying awscrt/crypto.py -> build/lib.linux-armv7l-cpython-312/awscrt
      copying awscrt/auth.py -> build/lib.linux-armv7l-cpython-312/awscrt
      copying awscrt/io.py -> build/lib.linux-armv7l-cpython-312/awscrt
      copying awscrt/checksums.py -> build/lib.linux-armv7l-cpython-312/awscrt
      copying awscrt/_test.py -> build/lib.linux-armv7l-cpython-312/awscrt
      copying awscrt/common.py -> build/lib.linux-armv7l-cpython-312/awscrt
      copying awscrt/__init__.py -> build/lib.linux-armv7l-cpython-312/awscrt
      copying awscrt/mqtt.py -> build/lib.linux-armv7l-cpython-312/awscrt
      creating build/lib.linux-armv7l-cpython-312/awscrt/eventstream
      copying awscrt/eventstream/rpc.py -> build/lib.linux-armv7l-cpython-312/awscrt/eventstream
      copying awscrt/eventstream/__init__.py -> build/lib.linux-armv7l-cpython-312/awscrt/eventstream
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ns3de30f/awscrt_1dd8d8835cbc48c58a93cebbfb8cad35/setup.py", line 399, in <module>
          setuptools.setup(
        File "/usr/local/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/usr/local/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.12/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-ns3de30f/awscrt_1dd8d8835cbc48c58a93cebbfb8cad35/setup.py", line 263, in run
          self._build_dependencies(dep_build_dir, dep_install_path)
        File "/tmp/pip-install-ns3de30f/awscrt_1dd8d8835cbc48c58a93cebbfb8cad35/setup.py", line 255, in _build_dependen                                                    cies
          self._build_dependencies_impl(build_dir, install_path)
        File "/tmp/pip-install-ns3de30f/awscrt_1dd8d8835cbc48c58a93cebbfb8cad35/setup.py", line 163, in _build_dependen                                                    cies_impl
          cmake = get_cmake_path()
                  ^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-ns3de30f/awscrt_1dd8d8835cbc48c58a93cebbfb8cad35/setup.py", line 122, in get_cmake_path
          raise Exception("CMake must be installed to build from source.")
      Exception: CMake must be installed to build from source.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for awscrt
  Running setup.py clean for awscrt
Failed to build awscrt
ERROR: Could not build wheels for awscrt, which is required to install pyproject.toml-based projects
`

**Comment by elad-bar** [comment]
Another attempt, pls try to remove from manifest awscrt,
If it's not working please try to run the command:
```bash
pip3 install awsiotsdk
```

According to forums when running it from raspberry pi, behavior is bit different and required using pip3 (of python3)

**Comment by sh00t2kill** [comment]
This looks like a problem with the core container, as cmake isn't installed.

**Comment by elad-bar** [comment]
@tigers75 which version of HA are you running?
In addition, did you try what i wrote 4 days ago?

Thanks

**Comment by tigers75** [comment]
> @tigers75 which version of HA are you running? In addition, did you try what i wrote 4 days ago?
> 
> Thanks

Sorry, was away from PC until today.
First attempt afer removing awscrt formt he manifest:
`Logger: homeassistant.setup
Source: setup.py:221
First occurred: 08:47:53 (1 occurrences)
Last logged: 08:47:53

Setup failed for custom integration 'mydolphin_plus': Requirements for mydolphin_plus not found: ['awsiotsdk'].`

Running the pip3 command:
`
pi@raspberrypi:/home/homeassistant/.homeassistant/custom_components/mydolphin_plus $ docker exec home-assistant pip3 install awsiotsdk
Looking in indexes: https://pypi.org/simple, https://wheels.home-assistant.io/musllinux-index/
Collecting awsiotsdk
  Downloading awsiotsdk-1.21.0-py3-none-any.whl.metadata (4.2 kB)
Collecting awscrt==0.20.2 (from awsiotsdk)
  Downloading awscrt-0.20.2.tar.gz (32.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 32.1/32.1 MB 5.4 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Downloading awsiotsdk-1.21.0-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.5/73.5 kB 7.4 MB/s eta 0:00:00
Building wheels for collected packages: awscrt
  Building wheel for awscrt (setup.py): started
  Building wheel for awscrt (setup.py): finished with status 'error'
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [68 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-armv7l-cpython-312
      creating build/lib.linux-armv7l-cpython-312/awscrt
      copying awscrt/websocket.py -> build/lib.linux-armv7l-cpython-312/awscrt
      copying awscrt/s3.py -> build/lib.linux-armv7l-cpython-312/awscrt
      copying awscrt/http.py -> build/lib.linux-armv7l-cpython-312/awscrt
      copying awscrt/mqtt5.py -> build/lib.linux-armv7l-cpython-312/awscrt
      copying awscrt/exceptions.py -> build/lib.linux-armv7l-cpython-312/awscrt
      copying awscrt/crypto.py -> build/lib.linux-armv7l-cpython-312/awscrt
      copying awscrt/auth.py -> build/lib.linux-armv7l-cpython-312/awscrt
      copying awscrt/io.py -> build/lib.linux-armv7l-cpython-312/awscrt
      copying awscrt/checksums.py -> build/lib.linux-armv7l-cpython-312/awscrt
      copying awscrt/_test.py -> build/lib.linux-armv7l-cpython-312/awscrt
      copying awscrt/common.py -> build/lib.linux-armv7l-cpython-312/awscrt
      copying awscrt/__init__.py -> build/lib.linux-armv7l-cpython-312/awscrt
      copying awscrt/mqtt.py -> build/lib.linux-armv7l-cpython-312/awscrt
      creating build/lib.linux-armv7l-cpython-312/awscrt/eventstream
      copying awscrt/eventstream/rpc.py -> build/lib.linux-armv7l-cpython-312/awscrt/eventstream
      copying awscrt/eventstream/__init__.py -> build/lib.linux-armv7l-cpython-312/awscrt/eventstream
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-_ln771o6/awscrt_5ff3fd4a87ff42e393b885da1124e4e7/setup.py", line 399, in <module>
          setuptools.setup(
        File "/usr/local/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/usr/local/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.12/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-_ln771o6/awscrt_5ff3fd4a87ff42e393b885da1124e4e7/setup.py", line 263, in run
          self._build_dependencies(dep_build_dir, dep_install_path)
        File "/tmp/pip-install-_ln771o6/awscrt_5ff3fd4a87ff42e393b885da1124e4e7/setup.py", line 255, in _build_dependencies
          self._build_dependencies_impl(build_dir, install_path)
        File "/tmp/pip-install-_ln771o6/awscrt_5ff3fd4a87ff42e393b885da1124e4e7/setup.py", line 163, in _build_dependencies_impl
          cmake = get_cmake_path()
                  ^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-_ln771o6/awscrt_5ff3fd4a87ff42e393b885da1124e4e7/setup.py", line 122, in get_cmake_path
          raise Exception("CMake must be installed to build from source.")
      Exception: CMake must be installed to build from source.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for awscrt
  Running setup.py clean for awscrt
Failed to build awscrt
ERROR: Could not build wheels for awscrt, which is required to install pyproject.toml-based projects
`

Isee there's and update so there's a new docker image available, will try to upgrade and see what happens

**Comment by elad-bar** [comment]
closing this issue as it is related to AWS IoT SDK v2 for Raspberry PI only, original issue that was related to the SDK in general fixed,
Please try to follow instructions avialable in the following [link](https://github.com/aws/aws-iot-device-sdk-python-v2/issues/150),
according to it, installation is lacking of latest CMake version that prevents it from getting built locally, custom component should not change it and it should be part of the installation / docker image of HA.
