### ISSUE TITLE
does not set supported color modes, this will stop working in Home Assistant Core 2025.3

### ISSUE THREAD

**Issue by MajorAutomation** [sh00t2kill/dolphin-robot#179]
Just saw this in the logs.... thought I would add.

Logger: homeassistant.components.light
Source: components/light/__init__.py:1269
integration: Light ([documentation](https://www.home-assistant.io/integrations/light), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+light%22))
First occurred: 09:46:27 (1 occurrences)
Last logged: 09:46:27

None (<class 'custom_components.mydolphin_plus.light.MyDolphinPlusLightEntity'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/sh00t2kill/dolphin-robot/issues

2024-03-17 09:46:27.723 WARNING (MainThread) [homeassistant.components.light] None (<class 'custom_components.mydolphin_plus.light.MyDolphinPlusLightEntity'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/sh00t2kill/dolphin-robot/issues

**Comment by elad-bar** [comment]
fix for it pending local testing, thanks for reporting this issue

**Comment by elad-bar** [comment]
will be fixed in v1.0.12

**Comment by MajorAutomation** [comment]
Legendary!

On 25 Apr 2024, at 3:02 PM, Elad Bar ***@***.***> wrote:

﻿

will be fixed in v1.0.12

**Comment by AnthonyBe** [comment]
I have Integration v1.0.12 and HA 2024.5.3 and I'm seeing a new variation of this error now. Note that the error wording has changed from `does not set supported color modes` to `does not report a color mode`.

`2024-05-11 12:08:15.436 WARNING (MainThread) [homeassistant.components.light] light.aquawize_aw6_led (<class 'custom_components.mydolphin_plus.light.MyDolphinPlusLightEntity'>) does not report a color mode, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/sh00t2kill/dolphin-robot/issues`

Diagnostic file attached.
[config_entry-mydolphin_plus-f51e3ee42c0fc67259d37e0f24eff881.json](https://github.com/sh00t2kill/dolphin-robot/files/15281385/config_entry-mydolphin_plus-f51e3ee42c0fc67259d37e0f24eff881.json)

**Comment by AnthonyBe** [comment]
I just updated to [v1.0.13b2](https://github.com/sh00t2kill/dolphin-robot/releases/tag/v1.0.13b2) and can confirm that I am no longer seeing this warning logged.

**Comment by elad-bar** [comment]
thanks @AnthonyBe will close the issue once will get to non beta release

**Comment by sh00t2kill** [comment]
Resolved by v1.0.13
