### ISSUE TITLE
Long shot: Any way to automate reloading when plugged in?

### ISSUE THREAD

**Issue by deadrubberboy** [sh00t2kill/dolphin-robot#182]
Hello,

Keep the robot unplugged safely in shed until it's in use. When I plug in I have to restart home assistant or reload integration at very least. I get it, and that makes sense. Just wondering if there was any way to prompt this when it reconnects to network or something? (have Eero integration that knows when it reconnects)

Thanks!

**Comment by sh00t2kill** [comment]
I think this is related to an issue we are working through re disconnecting.

**Comment by elad-bar** [comment]
dup #178
