### ISSUE TITLE
Need to Tell te liberty 400 Akku Version to walk to the wall to remove it from water

### ISSUE THREAD

**Issue by pos-ei-don** [sh00t2kill/dolphin-robot#184]
Has anyone a solution for this?

**Comment by elad-bar** [comment]
If you would like to ask question about operating the robot in general, pls do it in the integration forum over Discord

Thanks

**Comment by pos-ei-don** [comment]
So I have to use discord, which is forbidden here where I live? Strange.....

**Comment by elad-bar** [comment]
I understand, reopening, pls provide more details especially on the model

**Comment by sh00t2kill** [comment]
Do you have pickup mode in the dolphin app ? Does that work ?
Not all robots have the same functionality.

**Comment by Scope666** [comment]
I used to have an M400 that didn't have "official" pickup mode, that function didn't work with this integration, but it does with my M600 which DOES support it.

On the plus side the M400 didn't have "Floor Only" but I was still able to do it with this integration.

**Comment by sh00t2kill** [comment]
There are so many robot versions and they all behave differently. Assuming that @pos-ei-don you tried pickup mode and it didnt work?

What on earth does "Shake the Clicker and the Dolphin Liberty will climb the nearest wall for easy removal." --- that seems not a thing you do in the app?

**Comment by elad-bar** [comment]
it works with sound the clicker is doing when you knock it to the wall of the pool which is additional non-integration related as mentioend by @sh00t2kill,
other robots like with pick up mode can use the funcitonality available in the intergation.

closing the issue as nothing we can do in here, if you have suggestion based on your app / data you can extract from it to make it feasible for us to develop, please reopen and share

thanks
