### ISSUE TITLE
Icon Not Found When Setting Up Configuration

### ISSUE THREAD

**Issue by lordlala** [sh00t2kill/dolphin-robot#19]
After installing the custom component, when attempting to add and setup My Dolphin Plus in Settings > Devices > Add New Integration, there is an error where the image should be stating Icon not available.

![image](https://user-images.githubusercontent.com/14075692/192508434-bad047fa-6dbd-42ba-aa93-e585d9a98569.png)

**Comment by sh00t2kill** [comment]
@lordlala the PR to the brands repo has been merged by Frenk, so this should now be taken care of.

**Comment by elad-bar** [comment]
Looks like all icons are available:
![image](https://user-images.githubusercontent.com/3207137/192701317-feb48c7a-95a8-4557-8634-5c86fd1a8aaf.png)

![image](https://user-images.githubusercontent.com/3207137/192701121-7f86eae4-e8e2-4a8e-b13a-2b2105acbf33.png)

![image](https://user-images.githubusercontent.com/3207137/192701216-a4c97564-85bf-427a-a314-5deffa64bfa6.png)
