### ISSUE TITLE
HA 2024.5 - "StrEnum was used from mydolphin_plus, this is a deprecated alias"

### ISSUE THREAD

**Issue by AnthonyBe** [sh00t2kill/dolphin-robot#190]
Just upgraded from HA 2024.4.4 to 2024.5.1 and had the following warning logged:

`2024-05-04 20:33:05.931 WARNING (ImportExecutor_0) [homeassistant.backports.enum] StrEnum was used from mydolphin_plus, this is a deprecated alias which will be removed in HA Core 2025.5. Use enum.StrEnum instead, please report it to the author of the 'mydolphin_plus' custom integration`

**Comment by elad-bar** [comment]
Are you using the latest version of the integration?

**Comment by AnthonyBe** [comment]
Ah, apologies.
I'm using release branch but can see it is fixed in forthcoming v1.0.12 release.
