### ISSUE TITLE
Howto update the integration?

### ISSUE THREAD

**Issue by devinfluencer** [sh00t2kill/dolphin-robot#191]
Hi there,

dumb question, but how can I update the integration in HA? No update is offered, but I'm running 1.0.5 on HA 2024.5.2.

Thanks,
Thomas

**Comment by sh00t2kill** [comment]
Via HACS.
There are some threads on the forum re some people having hacs issues so it could be related to that. 

If hacs isn't working you can download the zip file and manually extract via smb/SSH.
