### ISSUE TITLE
New Loop Errors

### ISSUE THREAD

**Issue by MajorAutomation** [sh00t2kill/dolphin-robot#205]
Logger: homeassistant.util.loop
Source: util/loop.py:84
First occurred: 17:58:03 (11 occurrences)
Last logged: 17:58:03

Detected blocking call to open inside the event loop by custom integration 'mydolphin_plus' at custom_components/mydolphin_plus/managers/aws_client.py, line 202: client = mqtt_connection_builder.websockets_with_default_aws_signing( (offender: /usr/local/lib/python3.12/site-packages/awscrt/io.py, line 186: with open(filepath, mode='rb') as fh:), please create a bug report at https://github.com/sh00t2kill/dolphin-robot/issues 

Core
2024.6.4
Supervisor
2024.06.0
Operating System
12.4
Frontend
20240610.1

Logger: homeassistant.util.loop
Source: util/loop.py:84
First occurred: 17:58:03 (11 occurrences)
Last logged: 17:58:03

Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/util/logging.py", line 105, in _async_wrapper await async_func(*args) File "/config/custom_components/mydolphin_plus/managers/coordinator.py", line 300, in _on_api_status_changed await self._aws_client.initialize() File "/config/custom_components/mydolphin_plus/managers/aws_client.py", line 202, in initialize client = mqtt_connection_builder.websockets_with_default_aws_signing(
Detected blocking call to open inside the event loop by custom integration 'mydolphin_plus' at custom_components/mydolphin_plus/managers/aws_client.py, line 202: client = mqtt_connection_builder.websockets_with_default_aws_signing( (offender: /usr/local/lib/python3.12/site-packages/pkg_resources/__init__.py, line 1696: with open(path, 'rb') as stream:), please create a bug report at https://github.com/sh00t2kill/dolphin-robot/issues Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/util/logging.py", line 105, in _async_wrapper await async_func(*args) File "/config/custom_components/mydolphin_plus/managers/coordinator.py", line 300, in _on_api_status_changed await self._aws_client.initialize() File "/config/custom_components/mydolphin_plus/managers/aws_client.py", line 202, in initialize client = mqtt_connection_builder.websockets_with_default_aws_signing(

**Comment by MajorAutomation** [comment]
This was followed shortly afterwards

Logger: custom_components.mydolphin_plus.managers.coordinator
Source: custom_components/mydolphin_plus/managers/coordinator.py:406
integration: MyDolphin Plus ([documentation](https://github.com/sh00t2kill/dolphin-robot), [issues](https://github.com/sh00t2kill/dolphin-robot/issues))
First occurred: 17:59:54 (5 occurrences)
Last logged: 18:00:15

Failed to extract data for MyDolphinPlusSensorEntityDescription(key='temperature', device_class=<SensorDeviceClass.TEMPERATURE: 'temperature'>, entity_category=None, entity_registry_enabled_default=True, entity_registry_visible_default=True, force_update=False, icon=None, has_entity_name=False, name='Temperature', translation_key='temperature', translation_placeholders=None, unit_of_measurement=None, platform=<Platform.SENSOR: 'sensor'>, last_reset=None, native_unit_of_measurement=<UnitOfTemperature.CELSIUS: '°C'>, options=None, state_class=<SensorStateClass.MEASUREMENT: 'measurement'>, suggested_display_precision=None, suggested_unit_of_measurement=None), Error: 'str' object has no attribute 'get', Line: 400

**Comment by elad-bar** [comment]
2nd error is not relevant if it failed in first stage,
What version of integration are you using?

Thanks

**Comment by MajorAutomation** [comment]
1.0.13

On 22 Jun 2024, at 8:54 PM, Elad Bar ***@***.***> wrote:

﻿

2nd error is not relevant if it failed in first stage,
What version of integration are you using?

Thanks

**Comment by elad-bar** [comment]
Please upgrade to latest, such issues already solved,
Closing, if still relevant with latest, reopen and provide relevant details

Thanks

**Comment by MajorAutomation** [comment]
Says it's the latest version in HACS.

On 22 Jun 2024, at 9:00 PM, Elad Bar ***@***.***> wrote:

﻿

Please upgrade to latest, such issues already solved,
Closing, if still relevant with latest, reopen and provide relevant details

Thanks

**Comment by elad-bar** [comment]
https://github.com/sh00t2kill/dolphin-robot/releases/tag/v1.0.15

Force update in hacs, latest is v1.0.15
