### ISSUE TITLE
Time issue

### ISSUE THREAD

**Issue by sh00t2kill** [sh00t2kill/dolphin-robot#34]
There is potentially an issue with the time returned by the api.

Payload
```cycleInfo - {'cleaningMode': {'mode': 'all', 'cycleTime': 150}, 'cycleStartTime': 1664466304, 'cycleStartTimeUTC': 1664430336}```

Converting those using epochconverter.com
![image](https://user-images.githubusercontent.com/38101689/192983397-1a654d8d-8c06-4eb2-a39e-960c848849f7.png)

![image](https://user-images.githubusercontent.com/38101689/192983437-d48760ae-4b98-4a65-b653-c4515592357b.png)

You can see that UTC time is actually the current local time, and the current local time is 10 hours in the future.
I am currently at +10 timezone.

**Comment by elad-bar** [comment]
Should be solved in develop branch
