### ISSUE TITLE
any chance for bluetooth model support?

### ISSUE THREAD

**Issue by randrcomputers** [sh00t2kill/dolphin-robot#71]
Would be great to have support for bluetooth aswell.

**Comment by grouts112** [comment]
+1

**Comment by sh00t2kill** [comment]
No plans to do this at the moment. The bluetooth traffic appears to be encrypted.

**Comment by elad-bar** [comment]
closing, no plans to support,
if you would like to support it, you can try adding it within the Passive BLE monitor integration
