### ISSUE TITLE
Robot not related to user

### ISSUE THREAD

**Issue by gkyprios** [sh00t2kill/dolphin-robot#91]
Hi guys,

Firstly thanks for the custom integration. I was using my M600 in Home Automation mode and controlling power to it from the wall socket, but your integration is much, much better!

I seem to be having an issue with the initial setup though. I am running HA 2022.11.5 and HACS 1.28.4. Everything seems to install fine and the intergration is happy with my creds. But after taking my creds no entities are setup. According to the log I have this issue:

Logger: custom_components.mydolphin_plus.component.api.mydolphin_plus_api
Source: custom_components/mydolphin_plus/component/api/mydolphin_plus_api.py:151
Integration: MyDolphin Plus (documentation, issues)
First occurred: 11:02:09 (8 occurrences)
Last logged: 11:10:13

Failed to retrieve AWS token after 4 attempts, Error: Invalid length for a Base-64 char array or string.
Failed to retrieve AWS token after 4 attempts, Error: Robot not related to user

I have tried deleting the robot from the app and renaming it. I tried resetting my password just in case it was old and didnt comply with any new requirements, although it was authenticating correctly in the app and when I setup the Integration.

Let me know what else you might need to assist me please?

Thanks guys.

**Comment by sh00t2kill** [comment]
Can you please enable debugging and provide the logs?

The error suggests the serial number of the robot isn't being correctly determined.

**Comment by gkyprios** [comment]
Thanks for your response. No worries, see below. I think I removed all sensitive info but let me know if I missed anything?

The unit has gone back several times under warranty. I'm not sure if its the same one every time. Should I try to register the serial with them again?

[mydolphin.txt](https://github.com/sh00t2kill/dolphin-robot/files/10199022/mydolphin.txt)

Thanks again.

**Comment by sh00t2kill** [comment]
Is B3391DQM6K the correct serial for your current robot?

I wonder if it's changed but it's somehow pulling the wrong one.

It's definitely not credential related as it's logging in correctly

**Comment by gkyprios** [comment]
The serial numbers in the app appear to match the physical devices. But the serial for the robot is different to the serial for the motor:
![Screenshot_20221210_155952_MyDolphin Plus](https://user-images.githubusercontent.com/81947775/206834417-032bc7ba-f295-4a6b-9c0f-0987b2aaae4b.jpg)
![20221210_155532](https://user-images.githubusercontent.com/81947775/206834441-50f9a95c-f67f-434f-b481-cdbff0b8b7f1.jpg)

![20221210_155344](https://user-images.githubusercontent.com/81947775/206834457-ea14be75-ab38-451c-8145-1cadd500c586.jpg)

**Comment by sh00t2kill** [comment]
That explains it. The integration assumes they match. 

Will have a look at it.

**Comment by elad-bar** [comment]
adding more details to the login request / response, might find the reason over there

**Comment by elad-bar** [comment]
there are 2 options:
1. wait for v0.3.3 to get released
2. add the following line to `custom_components/mydolphin_plus/component/api/mydolphin_plus_api.py` (below line 179):
```python
                _LOGGER.debug(f"Logged in to user {username}, Data: {data}")
```
so it will look like (exactly) as in the image below 

![image](https://user-images.githubusercontent.com/3207137/206849615-90656dca-7b4f-4d56-896a-a0448fd18649.png)

**Comment by elad-bar** [comment]
most likely found the issue and fixed it for v0.3.3 (pending review by @sh00t2kill ),
the assumption was that the motor unit serial number is the same as the serial number without the last 2 characters,
instead of making that assumption, added new call to get it from Maytronics API.

**Comment by gkyprios** [comment]
Hey guys, I've added the extra line below 179 as above and restarted HA. Attached are the new logs.

[logs2.txt](https://github.com/sh00t2kill/dolphin-robot/files/10201238/logs2.txt)

Let me know what you need next?

**Comment by elad-bar** [comment]
As wrote in my last comment, solution is available but requires review before releasing it

**Comment by elad-bar** [comment]
Up until that version to be released you can take the dev branch and copy it to HA manually

**Comment by sh00t2kill** [comment]
v0.3.3 has been released.

**Comment by gkyprios** [comment]
Thanks very much guys. I'll let you know how I get on.

**Comment by gkyprios** [comment]
Thats working! Thanks guys!

**Comment by elad-bar** [comment]
Amazing, thanks for raising this issue and providing the logs to make it easier for us 😀
